//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPMathsOperationServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPMathsOperationServiceReference.ISoapService")]
    public interface ISoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/Addition", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.AdditionResponse> AdditionAsync(SOAPMathsOperationServiceReference.AdditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/Subtraction", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.SubtractionResponse> SubtractionAsync(SOAPMathsOperationServiceReference.SubtractionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/Multiplication", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.MultiplicationResponse> MultiplicationAsync(SOAPMathsOperationServiceReference.MultiplicationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.DivisionResponse> DivisionAsync(SOAPMathsOperationServiceReference.DivisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MulAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/Div", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivAsync(int num1, int num2);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdditionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Addition", Namespace="http://tempuri.org/", Order=0)]
        public SOAPMathsOperationServiceReference.AdditionRequestBody Body;
        
        public AdditionRequest()
        {
        }
        
        public AdditionRequest(SOAPMathsOperationServiceReference.AdditionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdditionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num2;
        
        public AdditionRequestBody()
        {
        }
        
        public AdditionRequestBody(int num1, int num2)
        {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdditionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdditionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPMathsOperationServiceReference.AdditionResponseBody Body;
        
        public AdditionResponse()
        {
        }
        
        public AdditionResponse(SOAPMathsOperationServiceReference.AdditionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdditionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdditionResult;
        
        public AdditionResponseBody()
        {
        }
        
        public AdditionResponseBody(string AdditionResult)
        {
            this.AdditionResult = AdditionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Subtraction", Namespace="http://tempuri.org/", Order=0)]
        public SOAPMathsOperationServiceReference.SubtractionRequestBody Body;
        
        public SubtractionRequest()
        {
        }
        
        public SubtractionRequest(SOAPMathsOperationServiceReference.SubtractionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num2;
        
        public SubtractionRequestBody()
        {
        }
        
        public SubtractionRequestBody(int num1, int num2)
        {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPMathsOperationServiceReference.SubtractionResponseBody Body;
        
        public SubtractionResponse()
        {
        }
        
        public SubtractionResponse(SOAPMathsOperationServiceReference.SubtractionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubtractionResult;
        
        public SubtractionResponseBody()
        {
        }
        
        public SubtractionResponseBody(string SubtractionResult)
        {
            this.SubtractionResult = SubtractionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplicationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Multiplication", Namespace="http://tempuri.org/", Order=0)]
        public SOAPMathsOperationServiceReference.MultiplicationRequestBody Body;
        
        public MultiplicationRequest()
        {
        }
        
        public MultiplicationRequest(SOAPMathsOperationServiceReference.MultiplicationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplicationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num2;
        
        public MultiplicationRequestBody()
        {
        }
        
        public MultiplicationRequestBody(int num1, int num2)
        {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplicationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiplicationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPMathsOperationServiceReference.MultiplicationResponseBody Body;
        
        public MultiplicationResponse()
        {
        }
        
        public MultiplicationResponse(SOAPMathsOperationServiceReference.MultiplicationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplicationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MultiplicationResult;
        
        public MultiplicationResponseBody()
        {
        }
        
        public MultiplicationResponseBody(string MultiplicationResult)
        {
            this.MultiplicationResult = MultiplicationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Division", Namespace="http://tempuri.org/", Order=0)]
        public SOAPMathsOperationServiceReference.DivisionRequestBody Body;
        
        public DivisionRequest()
        {
        }
        
        public DivisionRequest(SOAPMathsOperationServiceReference.DivisionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivisionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num2;
        
        public DivisionRequestBody()
        {
        }
        
        public DivisionRequestBody(int num1, int num2)
        {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DivisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPMathsOperationServiceReference.DivisionResponseBody Body;
        
        public DivisionResponse()
        {
        }
        
        public DivisionResponse(SOAPMathsOperationServiceReference.DivisionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivisionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DivisionResult;
        
        public DivisionResponseBody()
        {
        }
        
        public DivisionResponseBody(string DivisionResult)
        {
            this.DivisionResult = DivisionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ISoapServiceChannel : SOAPMathsOperationServiceReference.ISoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SoapServiceClient : System.ServiceModel.ClientBase<SOAPMathsOperationServiceReference.ISoapService>, SOAPMathsOperationServiceReference.ISoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SoapServiceClient() : 
                base(SoapServiceClient.GetDefaultBinding(), SoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISoapService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SoapServiceClient.GetBindingForEndpoint(endpointConfiguration), SoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.AdditionResponse> SOAPMathsOperationServiceReference.ISoapService.AdditionAsync(SOAPMathsOperationServiceReference.AdditionRequest request)
        {
            return base.Channel.AdditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.AdditionResponse> AdditionAsync(int num1, int num2)
        {
            SOAPMathsOperationServiceReference.AdditionRequest inValue = new SOAPMathsOperationServiceReference.AdditionRequest();
            inValue.Body = new SOAPMathsOperationServiceReference.AdditionRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((SOAPMathsOperationServiceReference.ISoapService)(this)).AdditionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.SubtractionResponse> SOAPMathsOperationServiceReference.ISoapService.SubtractionAsync(SOAPMathsOperationServiceReference.SubtractionRequest request)
        {
            return base.Channel.SubtractionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.SubtractionResponse> SubtractionAsync(int num1, int num2)
        {
            SOAPMathsOperationServiceReference.SubtractionRequest inValue = new SOAPMathsOperationServiceReference.SubtractionRequest();
            inValue.Body = new SOAPMathsOperationServiceReference.SubtractionRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((SOAPMathsOperationServiceReference.ISoapService)(this)).SubtractionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.MultiplicationResponse> SOAPMathsOperationServiceReference.ISoapService.MultiplicationAsync(SOAPMathsOperationServiceReference.MultiplicationRequest request)
        {
            return base.Channel.MultiplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.MultiplicationResponse> MultiplicationAsync(int num1, int num2)
        {
            SOAPMathsOperationServiceReference.MultiplicationRequest inValue = new SOAPMathsOperationServiceReference.MultiplicationRequest();
            inValue.Body = new SOAPMathsOperationServiceReference.MultiplicationRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((SOAPMathsOperationServiceReference.ISoapService)(this)).MultiplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.DivisionResponse> SOAPMathsOperationServiceReference.ISoapService.DivisionAsync(SOAPMathsOperationServiceReference.DivisionRequest request)
        {
            return base.Channel.DivisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPMathsOperationServiceReference.DivisionResponse> DivisionAsync(int num1, int num2)
        {
            SOAPMathsOperationServiceReference.DivisionRequest inValue = new SOAPMathsOperationServiceReference.DivisionRequest();
            inValue.Body = new SOAPMathsOperationServiceReference.DivisionRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((SOAPMathsOperationServiceReference.ISoapService)(this)).DivisionAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(int num1, int num2)
        {
            return base.Channel.SumAsync(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int num1, int num2)
        {
            return base.Channel.SubAsync(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> MulAsync(int num1, int num2)
        {
            return base.Channel.MulAsync(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> DivAsync(int num1, int num2)
        {
            return base.Channel.DivAsync(num1, num2);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISoapService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISoapService_soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5257/Services.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISoapService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISoapService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISoapService_soap,
        }
    }
}
